// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: cache.sql

package db

import (
	"context"
)

const createCache = `-- name: CreateCache :one
INSERT INTO caches (
  owner,
  title, 
  link
) VALUES (
  $1, $2, $3
) RETURNING id, owner, title, link, created_at
`

type CreateCacheParams struct {
	Owner string `json:"owner"`
	Title string `json:"title"`
	Link  string `json:"link"`
}

func (q *Queries) CreateCache(ctx context.Context, arg CreateCacheParams) (Cache, error) {
	row := q.db.QueryRow(ctx, createCache, arg.Owner, arg.Title, arg.Link)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Link,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM caches
WHERE id = $1
`

func (q *Queries) DeleteCache(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCache, id)
	return err
}

const getCache = `-- name: GetCache :one
SELECT id, owner, title, link, created_at FROM caches
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCache(ctx context.Context, id int64) (Cache, error) {
	row := q.db.QueryRow(ctx, getCache, id)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Link,
		&i.CreatedAt,
	)
	return i, err
}

const listCaches = `-- name: ListCaches :many
SELECT id, owner, title, link, created_at FROM caches
WHERE owner =$1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListCachesParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListCaches(ctx context.Context, arg ListCachesParams) ([]Cache, error) {
	rows, err := q.db.Query(ctx, listCaches, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cache{}
	for rows.Next() {
		var i Cache
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Title,
			&i.Link,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCache = `-- name: UpdateCache :one
UPDATE caches
SET title = $2,
    link = $3
WHERE id = $1
RETURNING id, owner, title, link, created_at
`

type UpdateCacheParams struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Link  string `json:"link"`
}

func (q *Queries) UpdateCache(ctx context.Context, arg UpdateCacheParams) (Cache, error) {
	row := q.db.QueryRow(ctx, updateCache, arg.ID, arg.Title, arg.Link)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Link,
		&i.CreatedAt,
	)
	return i, err
}
