// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCache(ctx context.Context, arg CreateCacheParams) (Cache, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCache(ctx context.Context, id int64) error
	GetCache(ctx context.Context, id int64) (Cache, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListCaches(ctx context.Context, arg ListCachesParams) ([]Cache, error)
	UpdateCache(ctx context.Context, arg UpdateCacheParams) (Cache, error)
}

var _ Querier = (*Queries)(nil)
